services:
  app:
    build:
      args:
        user: mona
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel:1.0.0
    container_name: pbf-docker-laravel
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - pbf-networks

  db:
    image: mysql:8.0
    container_name: pbf-docker-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_krs
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: user
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - pbf-networks

  nginx:
    image: nginx:alpine
    container_name: pbf-docker-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - pbf-networks

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pbf-docker-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 9001:80
    networks:
      - pbf-networks

networks:
  pbf-networks:
    driver: bridge